version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "additional/*"
      - "l10n/*"
      - "samples/*"
      - "tests/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"